name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "feature/Actions" ]
  pull_request:
    branches: [ "main", "feature/Actions" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
      # Migrating rails database for test env
      - name: Migrating db
        run: bundle exec bin/rails db:migrate RAILS_ENV=test
      # Run tests for rails, including rspec and cucumber
      - name: Run tests
        run: bundle exec rake
  
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: f3db11147c6cfdfc61faca0632f7c1c17202169eb096a171fe437a88432fc22e
        with:
          coverageCommand: bundle exec rake
          debug: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:          
          github-token: ${{ secrets.GITHUB_TOKEN }}
