name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "feature/Actions" ]
  pull_request:
    branches: [ "main", "feature/Actions" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
      # Add or replace test runners here
      - name: Run tests
        run: chmod -x bin/rake
      - name: CC Coverage
        uses: paambaati/codeclimate-action@v2.2.4
          env:
            CC_TEST_REPORTER_ID: 945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
          with:
            coverageCommand: rake spec

      # - name: Coveralls GitHub Action
  # You may pin to the exact commit or the version.
  # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        # uses: coverallsapp/github-action@1.1.3
        # with:
        #   # 
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   path-to-lcov: ./coverage/.resultset.json
        #   coveralls-endpoint: https://coveralls.io/github/leogrigs/EP-ESI
        #   # Coveralls Enterprise server (more info: https://enterprise.coveralls.io)
